version: "3"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    ports:
      - 9201:9200
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - EXCLUDE_PORTS=9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    networks:
      - dev
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    ports:
      - 9202:9200
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - EXCLUDE_PORTS=9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - dev
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    depends_on:
      - es01
      - es02
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - dev

volumes:
  esdata01:
  esdata02:

networks:
  dev:
    external:
      name: dev
